### ISSUE TITLE
Various issues with example spec (see debug console)

### ISSUE THREAD

**Issue by lemmy** [will62794/tla-web#10]
https://will62794.github.io/tla-web/?specpath=https://raw.githubusercontent.com/lemmy/tla-web/master/specs/EWD998.tla

**Comment by will62794** [comment]
Just did a bug-fixing pass, and think I ironed out most of the issues in EWD998. See updated version [here](https://will62794.github.io/tla-web/?specpath=./specs/EWD998.tla#), with only one [minor alteration](https://github.com/will62794/tla-web/blob/d970269525f0afb0e55cae0c950ba657e708483a/specs/EWD998.tla#L34-L35) to work around a remaining issue. Feel free to play around with it and see if you find any more bugs.

**Comment by lemmy** [comment]
Looks good; thanks for the quick fix.
