### ISSUE TITLE
Incomplete set of initial states

### ISSUE THREAD

**Issue by lemmy** [will62794/tla-web#15]
With e.g. EWD998 to `N == 2` and `Init!3` to `/\ color \in [Node -> {"white"}]`, there should be four initial states, but there are only three.

<img width="1240" alt="Screen Shot 2022-07-07 at 9 38 32 PM" src="https://user-images.githubusercontent.com/88777/177918331-39365239-bae5-4991-a018-341a360a6dcb.png">

**Comment by will62794** [comment]
Should be fixed with bb905b56.

See running demo [here](https://will62794.github.io/tla-web/?specpath=./specs/with_state_graphs/EWD998_regression1.tla#).

**Comment by lemmy** [comment]
Thanks, looks good.
