### ISSUE TITLE
Feature Request: ALIAS

### ISSUE THREAD

**Issue by fhackett-ms** [will62794/tla-web#23]
Hi - I'm Finn, a Microsoft Research intern working with @lemmy on some TLA+ specifications. You'll have seen me CC'd in one or two other issues. This issue is on the same theme, but now I'm closer to the polishing stage and have a bit more leeway to put effort into e.g tech for visualizing our work.
I'm trying to make this issue as complete as possible, so apologies if I re-state something you already know about.

When exploring more complex specifications, sometimes a feature of interest will not directly be in the state space. When in this situation, TLC offers the option (called `ALIAS`) to override the way it displays state, such that other features can be shown alongside / instead of the raw state variables.

Here's a heavily abridged fragment of something I'm working on that would benefit from this (I made sure this version works in the current explorer):
```tla
---- MODULE Example ----
EXTENDS Naturals, Sequences

VARIABLE log, idx

Init ==
    /\ log = <<>>
    /\ idx = 0

IncIdx ==
    /\ idx' = idx + 1
    /\ UNCHANGED log

JumpIdx ==
    /\ idx > 0
    /\ idx' \in 0..Len(log)
    /\ UNCHANGED log

GrowLog ==
    /\ log' = Append(log, idx)
    /\ UNCHANGED idx

Read ==
    IF   idx < Len(log)
    THEN {log[idx]}
    ELSE {}

Next ==
    \/ IncIdx
    \/ JumpIdx
    \/ GrowLog

Spec == Init /\ [][Next]_<<log, idx>>

Alias == [
    log |-> log,
    idx |-> idx,
    Read |-> Read
]

====
```

The take-away is that `Read` is derivable from any given state, but it might hard to calculate on the spot for humans, so having it spelled out in the visuals would improve the exploring experience for specs like this one. In particular, forcing someone unfamiliar with a spec to run one or more operator definitions in their heads as they try to understand a spec would be ... headache inducing.

From my perspective, an MVP implementation would be to look for an operator called `Alias` and, if it's there, assume it will yield a function associating a "virtual" set of state variables with a set of values to display at each state.

I have some cycles available to help develop such a thing, if that's of interest. Let me know if I should go and try to put together a PR.

**Comment by will62794** [comment]
@fhackett-ms Thanks for the request. I've definitely wanted to add a similar kind of "trace exploration" feature to the web interface but haven't gotten around to it yet. I put together a quick prototype that might get you going for now. See a demo running [here](https://will62794.github.io/tla-web/?specpath=./specs/LogExample.tla#). Not sure yet if this is the ideal way to implement this and display it in the UI, but it's a rough starting point for future iteration.

**Comment by fhackett-ms** [comment]
@will62794 Thanks for the quick update - that looks like a good start. I'll start trying my real spec with that change soon.

In the meantime, some thoughts:
- It would be really nice if the selection view also showed these extra values, so I could click on "the next-state where it reads X" or something like that
- I see you opted for appending `Alias` to the state display. If you're going in that direction, it would be good if each element of `Alias` were appended as a separate name-value binding, rather than the entire `Alias` value. That way, having 5-6 extra values (not too many, but too many to fit on one line) would be more readable.

**Comment by will62794** [comment]
@fhackett-ms Thanks for taking a look. I pushed a new iteration addressing some of your latest comments. See how it works for you (see same [demo spec](https://will62794.github.io/tla-web/?specpath=./specs/LogExample.tla#)). Happy to iterate on any other features you might find useful. Eventually I would also like to build in some kind of visualization capability, so that you could view a visual representation of each state of the trace. Perhaps defined via some kind of SVG-based DSL, or something like that. That's a longer term goal, though.

**Comment by lemmy** [comment]
FYI: With TLC, an alias is an action-level expression (https://github.com/tlaplus/tlaplus/issues/746#issuecomment-1200158771).

**Comment by fhackett-ms** [comment]
@will62794 I've tried the new iteration with my "real" spec as well, and it looks quite usable. Thank you!

My only remaining wish for this feature, optional as it is, is to have a collapsible tree view for compound values. It wouldn't need to be limited to Alias, it would just make some of my Alias values nicer to read.

Here's a quick example:
```tlaplus
---- MODULE LogExample ----

\* From https://github.com/will62794/tla-web/issues/23.

EXTENDS Naturals, Sequences

VARIABLE log, idxs

Keys == {"k1", "k2", "k3"}

Init ==
    /\ log = <<>>
    /\ idxs = [ key \in Keys |-> 0 ]

IncIdx(key) ==
    /\ idxs' = [ idxs EXCEPT ![key] = @ + 1 ]
    /\ UNCHANGED log

JumpIdx(key) ==
    /\ idxs[key] > 0
    /\ \E i \in 0..Len(log) :
    	/\ idxs' = [ idxs EXCEPT ![key] = i ]
    /\ UNCHANGED log

GrowLog(key) ==
    /\ log' = Append(log, idxs[key])
    /\ UNCHANGED idxs

Read(key) ==
    IF   idxs[key] < Len(log) /\ idxs[key] > 0
    THEN {log[idxs[key]]}
    ELSE {}

Next ==
	\E key \in Keys :
    	\/ IncIdx(key)
    	\/ JumpIdx(key)
    	\/ GrowLog(key)

Spec == Init /\ [][Next]_<<log, idxs>>

Alias == [
    Reads |-> [ key \in Keys |-> Read(key) ]
]

====
```

It would be nice to be able to expand/collapse keys, or at least to see a more formatted tree view where my eyes know where to go.

I tried some "fancy" ways to simulate the effect I want, but it turns out "flattening" function domains is not something TLA+ makes easy (that is, flattening while keeping all the key-value mappings intact...).

I did find that the Alias feature breaks everything when the function domain isn't names, though (I ended up with a domain of tuples during an experiment). Not like you need to support this meaningfully, but it could maybe discard the Alias with a red highlight or something:
```tlaplus
---- MODULE LogExample ----

\* From https://github.com/will62794/tla-web/issues/23.

EXTENDS Naturals, Sequences

VARIABLE log, idxs

Keys == {"k1", "k2", "k3"}

Init ==
    /\ log = <<>>
    /\ idxs = [ key \in Keys |-> 0 ]

IncIdx(key) ==
    /\ idxs' = [ idxs EXCEPT ![key] = @ + 1 ]
    /\ UNCHANGED log

JumpIdx(key) ==
    /\ idxs[key] > 0
    /\ \E i \in 0..Len(log) :
    	/\ idxs' = [ idxs EXCEPT ![key] = i ]
    /\ UNCHANGED log

GrowLog(key) ==
    /\ log' = Append(log, idxs[key])
    /\ UNCHANGED idxs

Read(key) ==
    IF   idxs[key] < Len(log) /\ idxs[key] > 0
    THEN {log[idxs[key]]}
    ELSE {}

Next ==
	\E key \in Keys :
    	\/ IncIdx(key)
    	\/ JumpIdx(key)
    	\/ GrowLog(key)

Spec == Init /\ [][Next]_<<log, idxs>>

Alias == [ pair \in { <<"read", key>> : key \in Keys } |-> Read(pair[2]) ]

====
```

**Comment by will62794** [comment]
Prototype implemented in 4fb8721.

**Comment by lemmy** [comment]
Is it possible to suppress the spec's variable and *only* show the alias?

**Comment by will62794** [comment]
A prototype of trace expressions is now pushed (b50fdb2), which should supersede the `Alias` feature. To your point, though, suppressing/hiding selected sets of state variables should be a relatively straightforward next step for me to implement.

**Comment by will62794** [comment]
Disabled in 4dad0b6, in favor of [trace expressions](https://github.com/will62794/tla-web/commit/b50fdb2099ceff2740dab5d2f03e5e050aa5158f).

**Comment by will62794** [comment]
@lemmy With 3e79c5d you should now be able to hide/unhide state variables in the current trace.
