### ISSUE TITLE
Can't use EXCEPT on sequences, or Append on sequence-domain functions

### ISSUE THREAD

**Issue by fhackett-ms** [will62794/tla-web#25]
Sometimes, you need to "reassign" part of a sequence in your next-state relation.

Here's a minimal example of what I mean (this spec does not work):
```tlaplus
---- MODULE test ----
EXTENDS Naturals

VARIABLE seq

Init ==
    /\ seq = <<1, 2, 3>>

Next ==
    /\ seq' = [seq EXCEPT ![1] = IF @ = 5 THEN 1 ELSE @ + 1]

Spec == Init /\ [][Next]_seq

====
```

This doesn't work currently, because I imagine EXCEPT's implementation asserts that it was given a function or record.
On its own, it would be nice if this worked. I think, however, that this exposes a slightly more fundamental things that could be addressed.

The problem is that it doesn't work the "other way round" either. I can sort of work around the issue like this (this spec works):
```tlaplus
---- MODULE test ----
EXTENDS Naturals

VARIABLE seq

Init ==
    /\ seq = <<1, 2, 3>>

Next ==
    /\ seq' = [ i \in DOMAIN seq |->
    	IF i = 1 THEN
        	IF seq[1] = 5 THEN 1 ELSE seq[1] + 1
        ELSE seq[i]]

Spec == Init /\ [][Next]_seq

====
```

The problem, then, becomes that I can't go back to using `seq` like a sequence. If I have a spec that uses both `EXCEPT` _and_ `Append` on the same value in alternation, then that itself becomes a problem. See this last example, which also does not work:
```tlaplus
---- MODULE test ----
EXTENDS Naturals, Sequences

VARIABLE seq

Init ==
    /\ seq = <<1, 2, 3>>

Inc ==
    /\ seq' = [ i \in DOMAIN seq |->
    	IF i = 1 THEN
        	IF seq[1] = 5 THEN 1 ELSE seq[1] + 1
        ELSE seq[i]]

App ==
	/\ seq' = Append(seq, seq[1])

Next ==
	\/ Inc
    \/ App

Spec == Init /\ [][Next]_seq

====
```

I guess, ultimately, it would be very nice if `<<0, 0, 0>> = [i \in DOMAIN {1, 2, 3} |-> 0]` (or, enough implementation edge cases to make this true for the user, at least).

Let me know if you'd like more test cases along this theme - I can probably come up with a couple more.

**Comment by will62794** [comment]
@fhackett-ms I believe most cases here should now be handled appropriately e.g. see the test cases [here](https://github.com/will62794/tla-web/blob/c2ca34051ef3370ebd2e7b6578f7dca2f7177574/specs/with_state_graphs/simple_fcn_polymorphism.tla) (which are run [here](https://will62794.github.io/tla-web/test?test=simple_fcn_polymorphism&debug=1)). Please point out any other cases that still aren't working as expected, or close the issue if it is resolved for you. 

Note: String values may be another edge case to deal with in this context, but it seems TLC may also have some unexpected behaviors in this case (e.g. see https://github.com/tlaplus/tlaplus/issues/512).
