### ISSUE TITLE
Lasso detection rules out behaviors

### ISSUE THREAD

**Issue by lemmy** [will62794/tla-web#31]
```tla
-------------------------------- MODULE S -------------------------------
VARIABLES p

Init == p = FALSE

Next == p' \in BOOLEAN
============================================================================
```

The evaluator won't let me generate a behavior such as F, T, T, F, ...  The moment when two consecutive states are equivalent, the back to state marker is added, causing, e.g., this example to become F, T, T, T, T, T, ....

**Comment by will62794** [comment]
Good point. I [reverted lasso detection](https://github.com/will62794/tla-web/commit/709bdbe68e7a8663eb40c1eb1cec0bf30ab07ce6) for now so you can generate behaviors with arbitrary sequences of repeated states. I added the lasso detection as an experiment but realize now it may not be exactly what we want. There may ultimately be a cleaner way to present lassos in the interface, but it's probably better to leave things simple for now.

**Comment by will62794** [comment]
Closing for now until I revisit how to handle this aspect of the explorer interface.
