### ISSUE TITLE
Can I embed this in another website?

### ISSUE THREAD

**Issue by hwayne** [will62794/tla-web#36]
1. This is amazingly cool, thank you for making this.
2. If possible, I think this would be a great addition to learntla. Is it something I can embed in another website? If so, how? No worries if this is impossible or would take too long to explain!

**Comment by will62794** [comment]
> This is amazingly cool, thank you for making this.

Thanks, glad you like it!

> Is it something I can embed in another website? If so, how?

Yes, in theory this should be totally possible and something I had started to think about a bit but hadn't looked at in depth or documented yet. 

I started to sketch out a basic sample of how you could, for example, embed just the interpreter itself in a stand alone web page. You can see a quick write up describing this [here](https://github.com/will62794/tla-web/blob/master/doc/embedding.md). In future it would be interesting to consider if UI components themselves from the tool could be embedded as well. I think this is possible and not too difficult, I would just need to give a it a bit more thought.

**Comment by will62794** [comment]
@hwayne Another small example of embedding on another page [here](https://will62794.github.io/formal-methods/specification/2024/12/12/interactive-formal-specs.html).
