### ISSUE TITLE
Should notify user if spec fails to load

### ISSUE THREAD

**Issue by hwayne** [will62794/tla-web#37]
Two cases I'm thinking of:

1. Loading a PlusCal file without translation will cause it to spin forever (since it can't translate the pluscal file)
2. Loading a github link like https://github.com/hwayne/tla-graphing-demo/blob/master/threads.tla will fail because it's not the raw link: you need https://raw.githubusercontent.com/hwayne/tla-graphing-demo/master/threads.tla

**Comment by will62794** [comment]
In general, there are a variety of error reporting features that can be improved upon in the tool, but I pushed a [few changes](https://github.com/will62794/tla-web/commit/be87b6920c0707c0cb1c037341b617441383ae97) that should help address (2) more clearly (i.e. cases where a spec can't be fetched properly from the given URL). 

For (1), I believe the tool will currently just report absence of an initial state predicate (`Init`) as an error if a PlusCal spec is given without any translation. For example, you can try loading [this raw spec](https://gist.githubusercontent.com/will62794/4a5eb91333f2f173dd7450ec7c31ac8d/raw/ba5d29c48b5fcc659da2b7b01b03ed493531c906/BinarySearch.tla). There may be some additional edge cases to consider when handling various PlusCal specs, but I haven't thought about it too carefully yet.
