### ISSUE TITLE
Multiline-comments between constants are treated as constants

### ISSUE THREAD

**Issue by lemmy** [will62794/tla-web#4]
<img width="951" alt="Screen Shot 2022-03-13 at 2 59 35 PM" src="https://user-images.githubusercontent.com/88777/158081010-5d407fb4-2ad0-4c42-a09f-2d7ca93cc974.png">

**Comment by will62794** [comment]
Ack'd. In general there are still a bunch of kinks to be worked out, in parsing, evaluation, etc.

**Comment by will62794** [comment]
This should be fixed as of 759a137.
