### ISSUE TITLE
Opening trace link loads forever

### ISSUE THREAD

**Issue by lemmy** [will62794/tla-web#41]
Opening the following trace link takes forever (spinning wheel next to "root spec") in Edge (Vivaldi) and Safari: https://will62794.github.io/tla-web/#!/home?specpath=https%3A%2F%2Fraw.githubusercontent.com%2Flemmy%2FCCF%2Fmku-ConsistencyMonolith%2Ftla%2Fconsistency%2FConsistency.tla&traceExprs%5B0%5D=AllCommittedObservedRoInv&trace=297cc69b%2Cd0b53816%2Cc64ffa94%2C28d6a04f%2C266f1e96%2C44617b58%2C551598da%2C150d05ea%2C14022610%2C74fe4aa9%2Cae2a49a2%2Cd54bbb48

**Comment by lemmy** [comment]
Screenshot of the tab in which I manually created the trace:

<img width="3060" alt="Screenshot 2024-05-05 at 10 48 43 AM" src="https://github.com/will62794/tla-web/assets/88777/63c4b5da-cbbf-4233-a580-f6ffbb5175e6">

**Comment by lemmy** [comment]
This might be due to the spec at the github url being out of date.

**Comment by lemmy** [comment]
This link works: https://will62794.github.io/tla-web/#!/home?specpath=https%3A%2F%2Fraw.githubusercontent.com%2Flemmy%2FCCF%2Fmku-ConsistencyMonolith%2Ftla%2Fconsistency%2FConsistency.tla&trace=297cc69b%2Cd0b53816%2Cc64ffa94%2C28d6a04f%2C266f1e96%2C44617b58%2C551598da%2C150d05ea%2C14022610%2C74fe4aa9%2Cae2a49a2%2Cd54bbb48&traceExprs%5B0%5D=AllCommittedObservedRoInv

**Comment by lemmy** [comment]
This was indeed caused by the spec being outdated.  Perhaps, add a checksum to links to gracefully fail if there is a mismatch.

**Comment by will62794** [comment]
Closing unless you believe there is some other underlying bug here.

**Comment by lemmy** [comment]
Like I said, the link could include a checksum over the spec, and error or warn if one loads an trace for a spec that does not match.
