### ISSUE TITLE
Parse error if Next is defined on one line

### ISSUE THREAD

**Issue by ajdavis** [will62794/tla-web#45]
This module causes a parse error, although it's correct syntax:
```
------------------------------- MODULE Conjunct ----------------------------- 
EXTENDS TLC, Naturals

VARIABLES x

Action1 == 1 = 2 /\ <<>>[0]
Action2 == x' = x + 1

Next == Action1 \/ Action 2
Init == x = 176
=============================================================================
```
Replace the `Next` definition thus to allow parsing:
```
Next ==
  \/ Action1
  \/ Action 2
```
The first module should parse identically.

**Comment by will62794** [comment]
The second disjunct of `Next` in the first spec seems to indeed be a syntax error (the extra space between `Action` and `2`) i.e.,
```
Next == Action1 \/ Action 2
```
Is this the same spec you were testing?

**Comment by ajdavis** [comment]
OMG, sorry.

**Comment by will62794** [comment]
No problem!
