### ISSUE TITLE
Support recursive operators

### ISSUE THREAD

**Issue by will62794** [will62794/tla-web#5]
Add support for recursive (`RECURSIVE`) operator definitions. See one [basic example](https://github.com/tlaplus/Examples/blob/9d7de44a8a37e415c8ba6e24d167632d53c24176/specifications/Stones/Stones.tla).

**Comment by lemmy** [comment]
FYI: Apalache no longer supports recursive functions or operators: https://apalache.informal.systems/docs/apalache/principles/recursive.html

**Comment by will62794** [comment]
At least partially supported by default for some [simple test cases](https://github.com/will62794/tla-web/blob/98ce0cf3c919376d0be9da9596652082aba5381c/specs/with_state_graphs/simple_recursive.tla).

**Comment by will62794** [comment]
Will test further in #33.
