### ISSUE TITLE
Disambiguate operator arguments named like variables

### ISSUE THREAD

**Issue by josefahmad** [will62794/tla-web#50]
In the presence of a global variable named `x` and operator whose argument is named `x` (e.g. `Operator(x) == x*2`), TLC interprets `x` inside the operator's expression as the operator's argument, while TLAWeb interprets it as the global variable.

**Comment by will62794** [comment]
Just to clarify, I am assuming you referring to a case like the following:
```tla
---- MODULE operator_name_clash_test ----
EXTENDS Naturals

VARIABLES x

Op(x) == x + 2

Init == x = 0
Next == x' = Op(x)

====
```

TLC treats this as an error, since it cannot disambiguate between the variable `x` and the argument `x` to operator `Op`. It appears, though, that the web explorer currently (and incorrectly) allows this. 

Is this the type of behavior you are referring to?

**Comment by josefahmad** [comment]
Here's a reproducer:
```
------------------------- MODULE operator_name_clash_test ------------------------------
EXTENDS Naturals

Intersect(s, x) ==
    IF s \intersect x # {} THEN 1 ELSE 2

VARIABLES x, v 

Init ==
    /\ x = 0
    /\ v = 0

Next ==
    /\ v' = Intersect(1..2, 3..4)
    /\ UNCHANGED x

vars == <<x, v>>
Spec == /\ Init /\ [][Next]_vars

-------------------------------------------------------------------------------

===============================================================================
```
Note the `Intersect` operator is declared before the variables. In this case, TLC doesn't treat this as an error and interprets the `x` in `Intersect` as `{3, 4}`. TLAWeb fails an internal assertion instead, and some initial stack trace inspection suggests that it treats `x` as the variable (natural number), rather than the operator's argument (set).

**Comment by josefahmad** [comment]
Thanks! Yes, `VARIABLE` name clashes seem to work as expected now. Want to keep this open for `CONSTANT` declarations, or close this one and fork a dedicated one for visiblity?

**Comment by will62794** [comment]
Keep it open for now. I'll try to address this for CONSTANT declarations soon.

**Comment by will62794** [comment]
CONSTANT declarations currently handled appropriately. See note and test in ee50d39, though.
